main:
    - nicfit.py
    - Pillow
    - pylast
    - requests

extra_facebook:
    - aioauth-client

test:
    - pytest
    - pytest-cov
    - pytest-runner
    - pytest-asyncio

dev:
    - nicfit.py[cookiecutter]
    - Sphinx
    - sphinx_rtd_theme
    - check-manifest
    - flake8
    - git+https://github.com/nicfit/gitchangelog.git
    - ipdb
    - pip-tools
    - tox
    - twine
    - wheel
    - pyaml
    - pss
